apiVersion: v1
kind: ConfigMap
metadata:
  name: oro-config-override
data:
  parameters.yml: |
    parameters:
        database_driver: pdo_pgsql
        database_host: {{ .Values.env.ORO_DB_HOST }}
        database_port: {{ .Values.env.ORO_DB_PORT }}
        database_name: {{ .Values.env.ORO_DB_NAME }}
        database_user: {{ .Values.env.ORO_DB_USER }}
        database_password: {{ .Values.env.ORO_DB_PASSWORD }}
        database_server_version: '15.12'
        
        # Redis configuration
        redis_dsn_cache: '{{ .Values.env.ORO_REDIS_DSN }}/1'
        redis_dsn_doctrine: '{{ .Values.env.ORO_REDIS_DSN }}/2'
        redis_dsn_layout: '{{ .Values.env.ORO_REDIS_DSN }}/3'
        redis_dsn_session: '{{ .Values.env.ORO_REDIS_DSN }}/0'
        
        # Search configuration
        search_engine_dsn: '{{ .Values.env.ORO_SEARCH_ENGINE_DSN }}'
        
        # App configuration
        secret: '{{ .Values.env.ORO_SECRET }}'
        mailer_dsn: '{{ .Values.env.ORO_MAILER_DSN }}'
        assets_version: ~
        assets_version_strategy: time_hash
        web_backend_prefix: '/admin'
        
        # Environment
        kernel.environment: {{ .Values.env.APP_ENV }}
        kernel.debug: false
        
        # Websocket settings (désactivés pour simplifier)
        websocket_bind_address: '0.0.0.0'
        websocket_bind_port: 8080
        websocket_frontend_host: '*'
        websocket_frontend_port: 8080
        websocket_frontend_path: ''
        websocket_backend_host: '*'
        websocket_backend_port: 8080
        websocket_backend_path: ''
        websocket_backend_transport: tcp
        websocket_frontend_transport: ws

  .env: |
    # Database configuration
    ORO_DB_DSN={{ .Values.env.ORO_DB_DSN }}

    # Redis configuration
    ORO_REDIS_URL={{ .Values.env.ORO_REDIS_DSN }}
    ORO_REDIS_CACHE_DSN={{ .Values.env.ORO_REDIS_DSN }}/1
    ORO_REDIS_DOCTRINE_DSN={{ .Values.env.ORO_REDIS_DSN }}/2
    ORO_REDIS_LAYOUT_DSN={{ .Values.env.ORO_REDIS_DSN }}/3

    # Search Engine configuration
    ORO_SEARCH_ENGINE_DSN={{ .Values.env.ORO_SEARCH_ENGINE_DSN }}

    # Mailer configuration
    ORO_MAILER_DSN={{ .Values.env.ORO_MAILER_DSN }}

    # Application settings
    ORO_SECRET={{ .Values.env.ORO_SECRET }}
    ORO_ASSETS_VERSION=1

    # Environment
    APP_ENV={{ .Values.env.APP_ENV }}
    APP_DEBUG=false
