apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oro-app-data
spec:
  accessModes: {{ .Values.persistence.accessModes }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
