apiVersion: v1
kind: Secret
metadata:
  name: orocommerce-secret
  labels:
    app: php-fpm-app
type: Opaque
data:
  # orodbpass = b3JvZGJwYXNz
  # admin123 = YWRtaW4xMjM=
  ORO_DB_PASSWORD: b3JvZGJwYXNz
  ORO_ADMIN_PASSWORD: YWRtaW4xMjM=
