apiVersion: batch/v1
kind: Job
metadata:
  name: oro-copy-files-v2
  labels:
    app: oro-copy-files
spec:
  template:
    metadata:
      labels:
        app: oro-copy-files
    spec:
      restartPolicy: OnFailure
      containers:
        - name: oro-copy-files
          image: oroinc/orocommerce-application-init:6.1.0
          command: 
            - sh
            - -c
            - |
              echo "Copie des fichiers OroCommerce..."
              echo "Contenu de /oro_init:"
              ls -la /oro_init/
              if [ -d /oro_init ]; then
                echo "Copie depuis /oro_init"
                cp -R /oro_init/* /var/www/oro/ 2>/dev/null || true
                find /oro_init -name "*.php" | head -5
              fi
              echo "Recherche de composer.json:"
              find / -name "composer.json" 2>/dev/null | head -5
              echo "Contenu final de /var/www/oro:"
              ls -la /var/www/oro/
          volumeMounts:
            - name: oro-app-data
              mountPath: /var/www/oro
      volumes:
        - name: oro-app-data
          persistentVolumeClaim:
            claimName: oro-app-data
