apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  labels:
    app: grafana
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: {{ .Values.datasources.prometheus.name }}
        type: {{ .Values.datasources.prometheus.type }}
        url: {{ .Values.datasources.prometheus.url }}
        access: {{ .Values.datasources.prometheus.access }}
        isDefault: {{ .Values.datasources.prometheus.isDefault }}
        editable: true
