apiVersion: v1
kind: Secret
metadata:
  name: grafana-secret
  labels:
    app: grafana
type: Opaque
data:
  # admin123 = YWRtaW4xMjM=
  # admin = YWRtaW4=
  GF_SECURITY_ADMIN_USER: YWRtaW4=
  GF_SECURITY_ADMIN_PASSWORD: YWRtaW4xMjM=
