apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secret
type: Opaque
data:
  POSTGRES_DB: {{ .Values.postgresql.db | b64enc | quote }}
  POSTGRES_USER: {{ .Values.postgresql.user | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.password | b64enc | quote }}
  POSTGRES_ROOT_PASSWORD: {{ .Values.postgresql.rootPassword | b64enc | quote }}