apiVersion: v1
kind: Service
metadata:
  name: postgresql
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5432
      protocol: TCP
      name: postgres
  selector:
    app: postgresql
