image:
  repository: grafana/grafana
  tag: 10.0.0
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  type: ClusterIP
  port: 3000

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi

persistence:
  enabled: true
  storageClass: ""
  accessMode: ReadWriteOnce
  size: 5Gi

adminUser: admin
adminPassword: admin123

datasources:
  prometheus:
    name: Prometheus
    type: prometheus
    url: http://prometheus:9090
    access: proxy
    isDefault: true

dashboards:
  enabled: true
  
env:
  GF_SECURITY_ADMIN_USER: admin
  GF_SECURITY_ADMIN_PASSWORD: admin123
  GF_USERS_ALLOW_SIGN_UP: false
  GF_INSTALL_PLUGINS: grafana-clock-panel,grafana-simple-json-datasource
